name: Непрерывная интеграция FastAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Линтинг с flake8
      run: |
        # остановить билд, если есть ошибки синтаксиса Python или неопределенные имена
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero считает все ошибки предупреждениями. Редактор GitHub имеет ширину 127 символов
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Тестирование с pytest
      run: |
        pytest tests/
        
    - name: Сборка и запуск приложения
      run: |
        uvicorn main:app --port 8000 --reload
